### ISSUE TITLE
Add action_type to API for use with Action Diary entries

### ISSUE THREAD

**Issue by gw-hackney** [LBHackney-IT/LBHTenancyAPI#111]
Good afternoon Selwyn and team,

Could you please urgently add support in the API for action_type with regards to setting Action Diary updates via the API. We need to send through action_type with value: 9 when updating cases.

Kind regards,

Guy

**Comment by LBHSPreston** [comment]
Good morning Guy. As discussed, we found that the action Action Diary post endpoint accepts a value for ActionCategory which records as action_type in the DB.
